name: Test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -  name: Repo metadata
       id: repo
       uses: actions/github-script@v3
       with:
        script: |
          const repo = await github.repos.get('https://github.com/home-assistant/core')
          return repo.data
    - name: Get repo inof
      run: echo "Repo ${{ steps.repo.outputs.result }}"
